# is a organization repository
organization: false

# site title
title: Just Do IT

# user name or organization name
user: zhiyue

# issue repository
repository: mirror-blog

# multi-author
authors:

# token
# token should be separated by '#'
# example: 5#c31bffc137f44faf7efc4a84da827g7ca2cfeaa
token: 0#acb3ff0f2ae0058c9d6edc52aa21a03657e0639

# posts per page
perpage: 20
